---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprblue-nxt
# description will be included in the image's metadata
description: This is my personal Hyprland OS image.

# the base image to build on top of (FROM) and the version tag to use
#base-image: quay.io/fedora/fedora-bootc
base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 41

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - from-file: common/common-modules.yml
  - from-file: common/hyprland-modules.yml
  - from-file: common/netbird-modules.yml
  - from-file: common/justfiles-modules.yml

  - type: signing

